services:
  app:
    container_name: AIS-worker
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/p7-ais/ais-worker:main
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
